version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: sales_db
    volumes:
      - ./db:/var/lib/postgresql/data  # This maps the local 'db' folder to the Postgres data folder
    ports:
      - "5432:5432"
    networks:
      - app_network

  web:
    build: .
    command: ["sh", "-c", "chmod +x /app/entrypoint.sh && /app/entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:  # This is a Docker volume that will persist data
    driver: local
